// Generated by CoffeeScript 1.7.1
Crafty.c('CenterText', {
  init: function() {
    this.requires('2D, DOM, Text');
    return this.attr({
      x: Game.width / 2,
      y: Game.height / 2
    });
  }
});

Crafty.c('Cell', {
  aliveColor: '#666',
  deadColor: '#123',
  currAlive: false,
  lastAlive: false,
  init: function() {
    this.requires('2D, Canvas, Color');
    this.attr({
      w: Game.cellSize,
      h: Game.cellSize
    });
    return this.cell(Crafty.math.randomInt(0, 1));
  },
  cell: function(state) {
    this.currAlive = !!state;
    this.lastAlive = !!state;
    this.color(this.cellColor());
    return this;
  },
  cellColor: function() {
    if (this.currAlive) {
      return this.aliveColor;
    } else {
      return this.deadColor;
    }
  },
  at: function(x, y) {
    return this.attr({
      x: x * Game.cellSize,
      y: y * Game.cellSize
    });
  }
});
