// Generated by CoffeeScript 1.7.1
var Game;

Game = {
  cellSize: 100,
  cellRows: function() {
    return Math.floor(this.height / this.cellSize);
  },
  cellColumns: function() {
    return Math.floor(this.width / this.cellSize);
  }
};
