// Generated by CoffeeScript 1.7.1
window.addEventListener('load', function() {
  Crafty.init();
  Game.width = Crafty.DOM.window.width;
  Game.height = Crafty.DOM.window.height;
  return Crafty.scene('Loading');
});
