// Generated by CoffeeScript 1.7.1
Crafty.scene('Loading', function() {
  Crafty.background('#FFF');
  Crafty.e('CenterText').text('Loading...');
  return Crafty.scene('GenerateBoard');
});

Crafty.scene('GenerateBoard', function() {
  var x, y, _i, _ref, _results;
  _results = [];
  for (x = _i = 0, _ref = Game.cellColumns(); 0 <= _ref ? _i <= _ref : _i >= _ref; x = 0 <= _ref ? ++_i : --_i) {
    _results.push((function() {
      var _j, _ref1, _results1;
      _results1 = [];
      for (y = _j = 0, _ref1 = Game.cellRows(); 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; y = 0 <= _ref1 ? ++_j : --_j) {
        _results1.push(Crafty.e('Cell').at(x, y));
      }
      return _results1;
    })());
  }
  return _results;
});
