// Generated by CoffeeScript 1.7.1
Crafty.scene('Loading', function() {
  Crafty.background('#FFF');
  Crafty.e('CenterText').text('Loading...');
  return Crafty.scene('GenerateBoard');
});

Crafty.scene('GenerateBoard', function() {
  var count, x, y, _i, _j, _ref, _ref1;
  for (x = _i = 0, _ref = Game.cellColumns(); 0 <= _ref ? _i < _ref : _i > _ref; x = 0 <= _ref ? ++_i : --_i) {
    for (y = _j = 0, _ref1 = Game.cellRows(); 0 <= _ref1 ? _j < _ref1 : _j > _ref1; y = 0 <= _ref1 ? ++_j : --_j) {
      Game.register(x, y, Crafty.e('Cell').at(x, y));
    }
  }
  Crafty.timer.FPS(1);
  Crafty.bind('EnterFrame', Game.advance);
  Crafty.bind('RenderScene', Game.reDraw);
  count = 0;
  return Crafty.bind('EnterFrame', function() {
    count += 1;
    if (count > 100) {
      return Crafty.pause();
    }
  });
});
